version: 2

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Check env vars
        command: if [[ -z "${DOCKER_LOGIN}" ]]; then echo "$DOCKER_LOGIN not set. Exiting."; exit -1; else echo "Env check OK."; fi
    - run:
        name: Clone liboqs
        command: cd integration/oqs_openssl && scripts/clone_liboqs.sh
    - run:
        name: Clone OpenSSL
        command: cd integration/oqs_openssl && scripts/clone_openssl.sh
    - run:
        name: Build liboqs
        command: source ~/.bashrc && cd integration/oqs_openssl && scripts/build_liboqs.sh
    - run:
        name: Build OpenSSL
        command: cd integration/oqs_openssl && scripts/build_openssl.sh
    - run:
        name: Run unit tests
        command: cd integration/oqs_openssl && python3 -m nose --rednose --verbose

jobs:
  ################
  # OPENSSL JOBS #
  ################
  ssl-x86_64-centos7-liboqs-master-openssl-111:
    <<: *openssljob
    environment:
      IMAGE: openqsafe/ci-centos7
      ARCH: x64
      LIBOQS: master
      LINKTYPE: dynamic
      OPENSSL: 111
      PREFIX: /opt/oqssa
      OPENSSL_DIR: /usr/local/ssl
  ssl-x86_64-alpine-liboqs-master-openssl-111:
    <<: *openssljob
    environment:
      IMAGE: openqsafe/ci-alpine
      ARCH: x64
      LIBOQS: master
      LINKTYPE: dynamic
      OPENSSL: 111
      PREFIX: /opt/oqssa
  ssl-x86_64-osx-liboqs-master-openssl-111:
     macos:
        xcode: "11.3.0"
     environment:
        OPENSSL: 111
        ARCH: x64_64
        LIBOQS: master
        LINKTYPE: dynamic
        PREFIX: /opt/oqssa
        OPENSSL_DIR: /usr/local/opt/openssl@1.1
     steps:
        - checkout 
        - run:
            name: Prep env
            command: brew update; brew unlink python@2; brew install autoconf automake libtool openssl wget doxygen graphviz; pip3 install pytest
        - run:
            name: Recon
            command: ls -l /usr/local; ls -l /usr/local/opt; openssl version; /usr/local/opt/openssl@1.1/bin/openssl version
        - run:
            name: Clone liboqs
            command: cd integration/oqs_openssl && scripts/clone_liboqs.sh
        - run:
            name: Clone OpenSSL
            command: cd integration/oqs_openssl && scripts/clone_openssl.sh
        - run:
            name: Build liboqs
            command: cd integration/oqs_openssl && scripts/build_liboqs.sh
        - run:
            name: Build OpenSSL
            command: cd integration/oqs_openssl && scripts/build_openssl.sh
        - run:
            name: Run unit tests
            command: cd integration/oqs_openssl && python3 -m nose --rednose --verbose

workflows:
  version: 2
  build:
    jobs:
            #- ssl-x86_64-centos7-liboqs-master-openssl-111:
            #  context: openqsafe
            #- ssl-x86_64-alpine-liboqs-master-openssl-111:
            #  context: openqsafe
      - ssl-x86_64-osx-liboqs-master-openssl-111:
              context: openqsafe

