version: 2

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Clone liboqs
        command: cd integration/oqs_openssl && scripts/clone_liboqs.sh
    - run:
        name: Clone OpenSSL
        command: cd integration/oqs_openssl && scripts/clone_openssl.sh
    - run:
        name: Build liboqs
        command: source ~/.bashrc && cd integration/oqs_openssl && scripts/build_liboqs.sh
    - run:
        name: Build OpenSSL
        command: source ~/.bashrc && cd integration/oqs_openssl && scripts/build_openssl.sh
    - run:
        name: Run unit tests
        command: cd integration/oqs_openssl && python3 -m nose --rednose --verbose

jobs:
  ################
  # OPENSSL JOBS #
  ################
  ssl-x86_64-centos7-liboqs-master-openssl-111:
    <<: *openssljob
    environment:
      IMAGE: openqsafe/ci-centos-7
      ARCH: x64
      LIBOQS: master
      LINKTYPE: dynamic
      OPENSSL: 111
      PREFIX: /opt/oqssa
      OPENSSL_DIR: /usr/local/ssl
  ssl-x86_64-centos8-liboqs-master-openssl-111:
    <<: *openssljob
    environment:
      IMAGE: openqsafe/ci-centos-8
      ARCH: x64
      LIBOQS: master
      LINKTYPE: dynamic
      OPENSSL: 111
      PREFIX: /opt/oqssa
  ssl-x86_64-alpine-liboqs-master-openssl-111:
    <<: *openssljob
    context: openqsafe
    environment:
      IMAGE: openqsafe/ci-alpine
      ARCH: x64
      LIBOQS: master
      LINKTYPE: dynamic
      OPENSSL: 111
      PREFIX: /opt/oqssa

workflows:
  version: 2
  build:
    jobs:
      - ssl-x86_64-centos8-liboqs-master-openssl-111
      - ssl-x86_64-centos7-liboqs-master-openssl-111
      - ssl-x86_64-alpine-liboqs-master-openssl-111

